### ISSUE TITLE
Missing styles on generated vue project

### ISSUE THREAD

**Issue by chinanf-boy** [vuegg/vuegg#4]
## ❤️amazing project😊

i want to report what I see

1. In` https://vuegg.now.sh/` , i selected a `Table` Component with `default setting`

2. I Download `Vuegg sources(.zip)`

3. `cd my-vuegg-project` &&` yarn` && `npm run start` then I see the `Table`

---

## in download project

![vuegg-table-issue](https://user-images.githubusercontent.com/20272484/36942264-3216b95a-1fa9-11e8-93aa-d7dd0d680c37.png)

``` css
th {
    font-weight: bold;
    text-align: -internal-center;
}
user agent stylesheet
td, th {
    display: table-cell;
    vertical-align: inherit;
}
```

---

## in `https://vuegg.now.sh/`

![web-vuegg-table](https://user-images.githubusercontent.com/20272484/36942283-a2a3bfce-1fa9-11e8-808b-5b2b6a15539c.png)

``` css
element.style {
    padding: 0px 8px;
}
/* here is diff*/
th {
    font-weight: bold;
    text-align: -internal-center;
}
user agent stylesheet
td, th {
    display: table-cell;
    vertical-align: inherit;
}
```
